export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST'
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS'
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL'

export const ADDRESS_EDIT_REQUEST = 'ADDRESS_EDIT_REQUEST'
export const ADDRESS_EDIT_SUCCESS = 'ADDRESS_EDIT_SUCCESS'
export const ADDRESS_EDIT_FAIL = 'ADDRESS_EDIT_FAIL'

export const ADDRESS_ADD_REQUEST = 'ADDRESS_ADD_REQUEST'
export const ADDRESS_ADD_SUCCESS = 'ADDRESS_ADD_SUCCESS'
export const ADDRESS_ADD_FAIL = 'ADDRESS_ADD_FAIL'