# Generated by Django 4.1.2 on 2022-10-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_shippingaddress_phone_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
