# Generated by Django 4.1.2 on 2022-11-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
