# Generated by Django 4.1.2 on 2022-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
