# Generated by Django 4.1.2 on 2022-11-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_order_address_remove_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='zipcode',
        ),
    ]
