# Generated by Django 4.1.2 on 2022-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_review_createdat_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
